version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/home/tak/dev/redmine/volume/mariadb:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '3000:3000'
    volumes:
      - '/home/tak/dev/redmine/volume/redmine:/bitnami/redmine'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
