version: '2'

services:

  redmine:
    build: ./redmine
    ports:
      - 127.0.0.1:3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    volumes:
      - ./volume/redmine/plugins:/usr/src/redmine/plugins
      - ./volume/redmine/files:/usr/src/redmine/files
      - ./volume/redmine/log:/usr/src/redmine/log
    restart: always

  db:
    build: ./mariadb
    volumes:
      - ./volume/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
