version: '2'

services:

  rm3redmine:
    build: ./redmine
    ports:
      - 127.0.0.1:3001:3000
    environment:
      REDMINE_DB_MYSQL: rm3db
      REDMINE_DB_USER: root
      REDMINE_DB_PASSWORD: example
    depends_on:
      - rm3db
    volumes:
      - ./volume/redmine/plugins:/usr/src/redmine/plugins
      - ./volume/redmine/files:/usr/src/redmine/files
      - ./volume/redmine/log:/usr/src/redmine/log
    links:
      - rm3db
    restart: always

  rm3db:
    image: library/mariadb:10.1.23
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volume/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always

  alpine:
    image: alpine:3.4
    
